safe: false
pygments: true
lsi: false
url: /datomisca
markdown: redcarpet
navigation:
- title: Home
  url: index.html
- title: Philosophy in Details
  url: doc/philosophy.html
- title: Features in Details
  url: doc/features.html
- title: Getting Started
  url: doc/getstarted.html
